# Generated by Django 3.2.7 on 2021-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/default.jpg', upload_to='post/'),
        ),
    ]
